version: '2'
services:
  cassandra:
    image: omarewedah/cassandra
    ports:
      - "9042:9042"

  cassandra2:
    image: omarewedah/cassandra
    ports:
      - "9043:9042"
    environment:
      SEED: cassandra

  cassandra3:
    image: omarewedah/cassandra
    ports:
      - "9044:9042"
    environment:
      SEED: cassandra
