version: '2'
services:
  cassandra:
    build: .
    ports:
      - "9042:9042"
    environment:
      SEED: 172.18.0.2
#      hosts: 172.17.0.2

  cassandra2:
    build: .
    ports:
      - "9043:9042"
    environment:
      SEED: 172.18.0.2
#      hosts: 172.17.0.3

  cassandra3:
    build: .
    ports:
      - "9044:9042"
    environment:
      SEED: 172.18.0.2
#      hosts: 172.17.0.15

